module.exports = {
    FETCH_MOVIES: "FETCH_MOVIES",
    GET_MOVIE: "GET_MOVIE",
    SEARCH_MOVIE: "SEARCH_MOVIE",
    ADD_MOVIE: "ADD_MOVIE",
    UPDATE_MOVIE: "UPDATE_MOVIE",
    DELETE_MOVIE: "DELETE_MOVIE"
};
